albums/urls.py
from django.urls import path
from albums.views import (
    AlbumListViewAlphabetically,
    AlbumDetailView,
    AlbumCreateView,
    AlbumUpdateView
)


urlpatterns = [
    path(
        '',
        AlbumListViewAlphabetically.as_view(), 
        name='album_list_alphabetically'
    ),
    path(
        '<int:pk>/',
        AlbumDetailView.as_view(),
        name='album_detail'
    ),
    path(
        'update/<int:pk>/',
        AlbumUpdateView.as_view(),
        name='album_update'
    ),
    path(
        'add/',
        AlbumCreateView.as_view(),
        name='add_album'
    ),
]

apis/urls.py
from django.urls import path
import apis.views as v

urlpatterns = [
    # albums
    path(
        'albums/',
        v.AlbumListAPIView.as_view(),
        name='api_albums_list'),
    path(
        'albums/<int:pk>/',
        v.AlbumDetailAPIView.as_view(),
        name='api_album_detail'),
    # bands
    path(
        'bands/',
        v.BandListAPIView.as_view(),
        name='api_bands_list'),
    path(
        'bands/<int:pk>/',
        v.BandDetailAPIView.as_view(),
        name='api_band_detail'),
    # labels
    path(
        'labels/',
        v.LabelListAPIView.as_view(),
        name='api_labels_list'),
    path(
        'labels/<int:pk>/',
        v.LabelDetailAPIView.as_view(),
        name='api_label_detail'),
    # musicians
    path(
        'musicians/',
        v.MusicianListAPIView.as_view(),
        name='api_musicians_list'),
    path(
        'musicians/<int:pk>/',
        v.MusicianDetailAPIView.as_view(),
        name='api_musician_detail'),
    # users
    path(
        'users/',
        v.UserListAPIView.as_view(),
        name='api_user_list'),
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView
)

urlpatterns = [
    # debug
    path('__debug__/', include('debug_toolbar.urls')),
    # admin
    path('admin/', admin.site.urls),
    # user management
    path('accounts/', include('allauth.urls')),
    # api
    path('api/v1/', include('apis.urls')),
    path('api-auth/', include('rest_framework.urls')),
    #schema
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path("api/schema/redoc/", SpectacularRedocView.as_view(
        url_name="schema"), name="redoc",),
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(
        url_name="schema"), name="swagger-ui"),
    # local apps
    path('', include('pages.urls')),
    path('genres/', include('genres.urls')),
    path('labels/', include('labels.urls')),
    path('musicians/', include('musicians.urls')),
    path('bands/', include('bands.urls')),
    path('musiciantoband/', include('musiciansbands.urls')),
    path('albums/', include('albums.urls')),
    path('reviews/', include('reviews.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

albums/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from bands.models import Band
from genres.models import Genre
from labels.models import Label


ALBUM_TYPES = [
    (1, 'Full-length'),
    (2, 'EP/Mini-albums'),
    (3, 'Compilation'),
    (4, 'Single'),
    (5, 'Mixtape'),
    (6, 'DJ Mix'),
    (7, 'Bootleg/Unauthorized'),
    (8, 'Live album'),
    (9, 'Video'),
    (10, 'Soundtrack'),
    (11, 'Promo'),
]


FORMAT_TYPES = [
    (1, 'CD'),
    (2, 'vinyl'),
    (3, 'cassette'),
    (4, 'CD/DVD'),
    (5, 'digibook'),
    (6, 'digital'),
    (7, 'all formats'),
]


class Album(models.Model):
    """Representation of the music album."""
    title = models.CharField(max_length=64)
    band = models.ForeignKey(
        Band,
        on_delete=models.CASCADE,
        related_name='album_by')
    genre = models.ManyToManyField(Genre)
    album_type = models.IntegerField(choices=ALBUM_TYPES)
    release_date = models.DateField(null=True)
    catalog_id = models.CharField(max_length=16)
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    album_format = models.IntegerField(choices=FORMAT_TYPES)
    cover = models.ImageField(upload_to='album_covers/')

    added = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Returns string representation of music album object."""
        return f'{self.title} by {self.band}'

    def get_absolute_url(self):
        """Gets an absolute url of single music album."""
        return reverse("album_detail", args=[str(self.id)])
        

albums/forms.py
from django.forms import ModelForm
from albums.models import Album


class AlbumCreationForm(ModelForm):
    class Meta:
        model = Album
        fields = [
            'title',
            'band',
            'genre',
            'album_type',
            'release_date',
            'catalog_id',
            'label',
            'album_format',
            'cover']

albums/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from albums.forms import AlbumCreationForm
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView
)
from albums.models import Album


class AlbumCreateView(LoginRequiredMixin, CreateView):
    """
    Creates an instance of the album.
    Only for logged-in users.
    """
    form_class = AlbumCreationForm
    success_url = reverse_lazy('home')
    template_name = 'albums/create_form.html'
    login_url = 'account_login'


class AlbumListViewAlphabetically(ListView):
    """Displays list of the albums in alphabetical order."""
    model = Album
    context_object_name = 'album_list'
    template_name = 'albums/album_list_alphabetically.html'
    paginate_by = 10
    ordering = 'title'


class AlbumDetailView(DetailView):
    """Displays a single album details."""
    model = Album
    context_object_name = 'album'
    template_name = 'albums/album_detail.html'


class AlbumUpdateView(LoginRequiredMixin, UpdateView):
    """
    Updates an instance of the album.
    Only for logged-in users.
    """
    model = Album
    form_class = AlbumCreationForm
    success_url = reverse_lazy('album_list_alphabetically')
    template_name = 'albums/create_form.html'

templates/albums/album_detail.html
{% extends '_base.html' %}

{% block title %}Album details{% endblock title %}

{% block content %}
    <div class="title">
        <h1>{{ album.title }} by <a href="{{ album.band.get_absolute_url }}">{{ album.band.name }}</a></h1>
    </div>
    <div class="details">
        <img class="album-cover" src="{{ album.cover.url }}" alt="{{ album.title }}">
    </div>
    <div class="details">
        <h3>Genre: {% for genre in album.genre.all %}{{ genre }}{% endfor %}</h3>
        <h3>Type: {{ album.get_album_type_display }}</h3>
        <h3>Release date: {{ album.release_date }}</h3>
        <h3>Catalog ID: {{ album.catalog_id }}</h3>
        <h3>Label: <a href="{{ album.label.get_absolute_url }}">{{ album.label }}</a></h3>
        <h3>Format: {{ album.get_album_format_display }}</h3>
    </div>
    <div class="adding-info">
        <p>Added: {{ album.added }}</p>
        <p>Added by: {{ album.added_by }}</p>
        <p>Modified: {{ album.modified }}</p>
    </div>
    <div>
        <a class="btn btn-success" href="{% url 'album_update' album.id%}" type="submit">Update info</a>
    </div>
{% endblock content %}

templates/albums/album_list_alphabetically.html
{% extends '_base.html' %}

{% block title %}Albums alphabetically{% endblock title %}

{% block content %}

    <div class="list-group">
        {% for album in album_list %}
            <a 
                href="{{ album.get_absolute_url }}" 
                class="list-group-item list-group-item-action"
            >
            {{ album.title }} by {{ album.band.name }}
            </a>
        {% endfor %}
    </div>

{%endblock content %}

templates/albums/create_form.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add new album{% endblock title %}

{% block content %}
    <h2>Add new album</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy}}
        <button class="btn btn-success" type="submit">Add</button>
    </form>
{% endblock content %}